name: Client Build Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Docker
        run: |
          docker --version

      - name: Install Dependencies
        run: |
          npm install

      - name: Build and push Docker image Client
        run: |
          docker build -t buihaoquang/hlshop:v1 .
          docker login -u buihaoquang -p bhquang1234567890
          docker push buihaoquang/hlshop:v1
